create database Ban_Ao_DB
go
use Ban_Ao_DB

go
IF OBJECT_ID('THUONG_HIEU') IS NOT NULL
DROP TABLE THUONG_HIEU
CREATE TABLE THUONG_HIEU (
ID INT IDENTITY(1,1) PRIMARY KEY,
TEN_THUONG_HIEU NVARCHAR(225) NOT NULL,
 MA_THUONG_HIEU VARCHAR(10),
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME
)
GO
IF OBJECT_ID('CHAT_LIEU') IS NOT NULL
DROP TABLE CHAT_LIEU
CREATE TABLE CHAT_LIEU (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_CHAT_LIEU VARCHAR(12) ,
TEN_CHAT_LIEU NVARCHAR(225) ,
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME
)
GO
IF OBJECT_ID('DANH_MUC') IS NOT NULL
DROP TABLE DANH_MUC
CREATE TABLE DANH_MUC (
ID INT IDENTITY(1,1) PRIMARY KEY,
TEN_DANH_MUC NVARCHAR(225) NOT NULL,
MA_DANH_MUC VARCHAR(10),
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME
)
GO
IF OBJECT_ID('NHA_SAN_XUAT') IS NOT NULL
DROP TABLE NHA_SAN_XUAT
CREATE TABLE NHA_SAN_XUAT (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_NHA_SAN_XUAT VARCHAR(12) ,
TEN_NHA_SAN_XUAT NVARCHAR(225) ,
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE(),
NGAY_SUA DATETIME
)
GO
IF OBJECT_ID('CO_AO') IS NOT NULL
DROP TABLE CO_AO
CREATE TABLE CO_AO (
ID INT IDENTITY(1,1) PRIMARY KEY,
TEN_CO_AO NVARCHAR(225) ,
MA_CO_AO VARCHAR(10),
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME
)
GO
IF OBJECT_ID('SAN_PHAM') IS NOT NULL
DROP TABLE SAN_PHAM
CREATE TABLE SAN_PHAM (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_SAN_PHAM VARCHAR(12) ,
TEN_SAN_PHAM NVARCHAR(255),
ANH_SAN_PHAM NVARCHAR(255),
NGAY_TAO DATETIME DEFAULT GETDATE(),
NGAY_SUA DATETIME,
ID_DANH_MUC INT,
ID_NHA_SAN_XUAT INT,
SO_LUONG_SAN_PHAM INT,
ID_THUONG_HIEU INT,
ID_CO_AO INT,
ID_CHAT_LIEU INT,
TRANG_THAI BIT,
CONSTRAINT FK_SAN_PHAM_CHAT_LIEU FOREIGN KEY(ID_CHAT_LIEU) REFERENCES CHAT_LIEU(ID),
CONSTRAINT FK_SAN_PHAM_DANH_MUC FOREIGN KEY(ID_DANH_MUC) REFERENCES DANH_MUC(ID),
CONSTRAINT FK_SAN_PHAM_NHA_SAN_XUA FOREIGN KEY(ID_NHA_SAN_XUAT) REFERENCES NHA_SAN_XUAT(ID),
CONSTRAINT FK_SAN_PHAM_THUONG_HIEU FOREIGN KEY(ID_THUONG_HIEU) REFERENCES THUONG_HIEU(ID),
CONSTRAINT FK_SAN_PHAM_CO_AO FOREIGN KEY(ID_CO_AO) REFERENCES CO_AO (ID),
)
GO
IF OBJECT_ID('KICH_THUOC') IS NOT NULL
DROP TABLE KICH_THUOC
CREATE TABLE KICH_THUOC (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_KICH_THUOC VARCHAR(10),
TEN_KICH_THUOC NVARCHAR(225) ,
TRANG_THAI BIT,
NGAY_TAO  DATETIME DEFAULT GETDATE(),
NGAY_SUA DATETIME
)

GO
IF OBJECT_ID('MAU_SAC') IS NOT NULL
DROP TABLE MAU_SAC
CREATE TABLE MAU_SAC (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_MAU_SAC VARCHAR(10),
TEN_MAU_SAC NVARCHAR(225) ,
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE(),
NGAY_SUA DATETIME,
)
GO
IF OBJECT_ID('SAN_PHAM_CHI_TIET') IS NOT NULL
DROP TABLE SAN_PHAM_CHI_TIET
CREATE TABLE SAN_PHAM_CHI_TIET (
ID INT IDENTITY(1,1) PRIMARY KEY,
ANH_SAN_PHAM_CHI_TIET NVARCHAR(255),
ID_SAN_PHAM INT,
ID_KICH_THUOC INT,
ID_MAU_SAC INT,
SO_LUONG_SAN_PHAM_CHI_TIET INT,
DON_GIA DECIMAL(10, 2),
MO_TA NVARCHAR(255) ,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME,
TRANG_THAI BIT,
CONSTRAINT FK_SAN_PHAM_CHI_TIET_SAN_PHAM FOREIGN KEY(ID_SAN_PHAM) REFERENCES SAN_PHAM(ID),
CONSTRAINT FK_SAN_PHAM_CHI_TIET_KICH_THUOC FOREIGN KEY(ID_KICH_THUOC) REFERENCES KICH_THUOC(ID),
CONSTRAINT FK_SAN_PHAM_CHI_TIET_MAU_SAC FOREIGN KEY(ID_MAU_SAC) REFERENCES MAU_SAC(ID),
)
GO

GO
IF OBJECT_ID('KHACH_HANG') IS NOT NULL
DROP TABLE KHACH_HANG
CREATE TABLE KHACH_HANG (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_KHACH_HANG NVARCHAR(225) ,
TEN_TAI_KHOAN NVARCHAR(225) ,
MAT_KHAU VARCHAR(15),
SO_DIEN_THOAI VARCHAR(12),
DIA_CHI NVARCHAR(225),
TEN_KHACH_HANG NVARCHAR(225) ,
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME,
)
GO
IF OBJECT_ID('GIO_HANG') IS NOT NULL
DROP TABLE GIO_HANG
CREATE TABLE GIO_HANG (
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_KHACH_HANG INT ,
ID_SAN_PHAM_CHI_TIET INT ,
SO_LUONG INT,
TONG_TIEN DECIMAL(10,2),
CONSTRAINT FK_GIO_HANG_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
CONSTRAINT FK_GIO_HANG_SAN_PHAM_CHI_TIET FOREIGN KEY (ID_SAN_PHAM_CHI_TIET) REFERENCES SAN_PHAM_CHI_TIET (ID),
)
GO
IF OBJECT_ID('NHAN_VIEN') IS NOT NULL
DROP TABLE NHAN_VIEN
CREATE TABLE NHAN_VIEN (
ID INT IDENTITY(1,1) PRIMARY KEY,
TEN_NHAN_VIEN NVARCHAR(225) ,
MA_NHAN_VIEN VARCHAR(225) ,
TEN_TAI_KHOAN VARCHAR(225) ,
MAT_KHAU VARCHAR(15),
CHUC_VU VARCHAR(255),
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME,
)
GO
IF OBJECT_ID('HOA_DON') IS NOT NULL
DROP TABLE HOA_DON
CREATE TABLE HOA_DON (
ID INT IDENTITY(1,1) PRIMARY KEY,
MAHD VARCHAR(10),
ID_NHAN_VIEN INT ,
SO_LUONG INT ,
DON_GIA DECIMAL(10,2) ,
SO_DIEN_THOAI VARCHAR(12) ,
ID_KHACH_HANG INT ,
TONG_TIEN DECIMAL(10,2) ,
NGAY_MUA DATETIME DEFAULT GETDATE(),
TRANG_THAI BIT,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME,
THANH_TIEN DECIMAL(10,2),
CONSTRAINT FK_HOA_DON_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (ID_NHAN_VIEN) REFERENCES NHAN_VIEN (ID),
)
GO
IF OBJECT_ID('THANH_TOAN') IS NOT NULL
DROP TABLE THANH_TOAN
CREATE TABLE THANH_TOAN (
ID INT IDENTITY(1,1) PRIMARY KEY,
HINH_THUC_THANH_TOAN INT ,
ID_KHACH_HANG INT ,
ID_HOA_DON INT ,
CONSTRAINT FK_THANH_TOAN_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
CONSTRAINT FK_THANH_TOAN_HOA_DON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON (ID),

)
GO
IF OBJECT_ID('HOA_DON_CHI_TIET') IS NOT NULL
DROP TABLE HOA_DON_CHI_TIET
CREATE TABLE HOA_DON_CHI_TIET (
ID INT IDENTITY(1,1) PRIMARY KEY,
MAHDCT VARCHAR(10) ,
ID_NHAN_VIEN INT ,
ID_SAN_PHAM INT ,
ID_HOA_DON INT ,
SO_LUONG INT,
DON_GIA DECIMAL(10,2) ,
NGAY_TAO DATETIME DEFAULT GETDATE() ,
NGAY_SUA DATETIME,
TONG_TIEN  DECIMAL(10,2),
HINH_THUC_THANH_TOAN NVARCHAR(255)
CONSTRAINT FK_HOA_DON_CHI_TIET_SAN_PHAM FOREIGN KEY (ID_SAN_PHAM) REFERENCES SAN_PHAM (ID),
CONSTRAINT FK_HOA_DON_CHI_TIET_HOA_DON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON (ID),
)
GO
IF OBJECT_ID('DOI_TRA') IS NOT NULL
DROP TABLE DOI_TRA
CREATE TABLE DOI_TRA (
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_KHACH_HANG INT ,
LY_DO_DOI NVARCHAR(255) ,
NGAY_DOI_TRA DATETIME,
TRANG_THAI BIT ,
MO_MA NVARCHAR(255),
ID_HOA_DON_CHI_TIET INT,
HINH_THUC_THANH_TOAN NVARCHAR(255) 
CONSTRAINT FK_DOI_TRA_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
CONSTRAINT FK_DOI_TRA_HOA_DON_CHI_TIET FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
)
GO
IF OBJECT_ID('SAN_PHAM_LOI') IS NOT NULL
DROP TABLE SAN_PHAM_LOI
CREATE TABLE SAN_PHAM_LOI (
ID INT IDENTITY(1,1) PRIMARY KEY,
TEN_SAN_PHAM_LOI NVARCHAR(255),
MO_MA NVARCHAR(255),
ID_HOA_DON_CHI_TIET INT,
SO_LUONG INT ,
CONSTRAINT FK_SAN_PHAM_LOI_HOA_DON_CHI_TIET FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
)

GO
IF OBJECT_ID('VOUCHER') IS NOT NULL
DROP TABLE VOUCHER
CREATE TABLE VOUCHER (
ID INT IDENTITY(1,1) PRIMARY KEY,
MA_KHUYEN_MAI NVARCHAR(255),
MA_AP_DUNG VARCHAR(50),
MO_MA NVARCHAR(255),
TEN_KHUYEN_MAI NVARCHAR(255),
NGAY_BAT_DAU DATETIME DEFAULT GETDATE(),
NGAY_KET_THUC DATETIME ,
MUC_GIAM VARCHAR(100),
TRANG_THAI BIT,
Loai Bit,
So_Luong Nvarchar(10),
DIEU_KIEN_KHUYEN_MAI NVARCHAR(255),
)
GO
IF OBJECT_ID('HOA_DON_VOUCHER') IS NOT NULL
DROP TABLE HOA_DON_VOUCHER
CREATE TABLE HOA_DON_VOUCHER (
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_VOUCHER INT ,
ID_HOA_DON_CHI_TIET INT,
SO_TIEN_CON_LAI DECIMAL(10,2) ,
CONSTRAINT FK_HOA_DON_VOUCHER_VOUCHER FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER (ID),
CONSTRAINT FK_HOA_DON_VOUCHER_HOA_DON_CHI_TIEN FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
)

-- Thêm dữ liệu vào bảng THUONG_HIEU
INSERT INTO THUONG_HIEU (TEN_THUONG_HIEU, MA_THUONG_HIEU)
VALUES
(N'Nike', 'NIKE001'),
(N'Adidas', 'ADI002');

-- Thêm dữ liệu vào bảng DANH_MUC
INSERT INTO DANH_MUC (TEN_DANH_MUC, MA_DANH_MUC, TRANG_THAI)
VALUES
(N'Thời trang nam', 'MEN001', 1),
(N'Thời trang nữ', 'WOM001', 1);

-- Thêm dữ liệu vào bảng CO_AO
INSERT INTO CO_AO (TEN_CO_AO, MA_CO_AO, TRANG_THAI)
VALUES
(N'Cổ tròn', 'CO001', 1),
(N'Cổ V', 'CO002', 1);

-- Thêm dữ liệu vào bảng CHAT_LIEU
INSERT INTO CHAT_LIEU (MA_CHAT_LIEU, TEN_CHAT_LIEU, TRANG_THAI)
VALUES
('CL001', N'Cotton', 1),
('CL002', N'Polyester', 1);

-- Thêm dữ liệu vào bảng NHA_SAN_XUAT
INSERT INTO NHA_SAN_XUAT (MA_NHA_SAN_XUAT, TEN_NHA_SAN_XUAT, TRANG_THAI)
VALUES
('NSX001', N'ABC Corp', 1),
('NSX002', N'XYZ Ltd', 1);

-- Thêm dữ liệu vào bảng SAN_PHAM
INSERT INTO SAN_PHAM (MA_SAN_PHAM, TEN_SAN_PHAM,ID_CHAT_LIEU, ANH_SAN_PHAM, ID_DANH_MUC, ID_NHA_SAN_XUAT, SO_LUONG_SAN_PHAM, ID_THUONG_HIEU, ID_CO_AO, TRANG_THAI)
VALUES
('SP001', N'Áo thun nam',2, 'aothun_nam.jpg', 1, 1, 100, 1, 1, 1),
('SP002', N'Áo sơ mi nữ',1, 'aosomi_nu.jpg', 2, 2, 50, 2, 2, 1);

-- Thêm dữ liệu vào bảng KICH_THUOC
INSERT INTO KICH_THUOC (MA_KICH_THUOC, TEN_KICH_THUOC, TRANG_THAI)
VALUES
('KT001', 'Size S', 1),
('KT002', 'Size M', 1);

-- Thêm dữ liệu vào bảng MAU_SAC
INSERT INTO MAU_SAC (MA_MAU_SAC, TEN_MAU_SAC, TRANG_THAI)
VALUES
('MS001', N'Đỏ', 1),
('MS002', N'Xanh', 1);

-- Thêm dữ liệu vào bảng SAN_PHAM_CHI_TIET
INSERT INTO SAN_PHAM_CHI_TIET (ANH_SAN_PHAM_CHI_TIET, ID_SAN_PHAM, ID_KICH_THUOC, ID_MAU_SAC, SO_LUONG_SAN_PHAM_CHI_TIET, DON_GIA, MO_TA, TRANG_THAI)
VALUES
('spct001.jpg', 1, 1, 1, 20, 200000, N'Áo thun nam màu đỏ, size S, chất liệu cotton', 1),
('spct002.jpg', 2, 2, 2, 15, 300000, N'Áo sơ mi nữ màu xanh, size M, chất liệu polyester', 1);

-- Thêm dữ liệu vào bảng KHACH_HANG
INSERT INTO KHACH_HANG (MA_KHACH_HANG, TEN_TAI_KHOAN, MAT_KHAU, SO_DIEN_THOAI, DIA_CHI, TEN_KHACH_HANG, TRANG_THAI)
VALUES
('KH001', 'taikhoan1', 'matkhau1', '0123456789', N'123 Đường A', N'Nguyễn Văn A', 1),
('KH002', 'taikhoan2', 'matkhau2', '0987654321', N'456 Đường B', N'Trần Thị B', 1);

-- Thêm dữ liệu vào bảng NHAN_VIEN
INSERT INTO NHAN_VIEN (TEN_NHAN_VIEN, MA_NHAN_VIEN, TEN_TAI_KHOAN, MAT_KHAU, CHUC_VU, TRANG_THAI)
VALUES
(N'Nguyễn Văn C', 'NV001', 'nvtaikhoan1', 'nvmatkhau1',N'Quản lý', 1),
(N'Trần Thị D', 'NV002', 'nvtaikhoan2', 'nvmatkhau2', N'Nhân viên', 1);

-- Thêm dữ liệu vào bảng HOA_DON
INSERT INTO HOA_DON (MAHD, ID_NHAN_VIEN, SO_LUONG, DON_GIA, SO_DIEN_THOAI, ID_KHACH_HANG, TONG_TIEN, THANH_TIEN, TRANG_THAI)
VALUES
('HD001', 1, 2, 400000, '0123456789', 1, 800000, 800000, 1),
('HD002', 2, 1, 300000, '0987654321', 2, 300000, 300000, 1);

-- Thêm dữ liệu vào bảng THANH_TOAN
INSERT INTO THANH_TOAN (HINH_THUC_THANH_TOAN, ID_KHACH_HANG, ID_HOA_DON)
VALUES
(1, 1, 1),
(2, 2, 2);

-- Thêm dữ liệu vào bảng HOA_DON_CHI_TIET
INSERT INTO HOA_DON_CHI_TIET (MAHDCT, ID_NHAN_VIEN, ID_SAN_PHAM, ID_HOA_DON, SO_LUONG, DON_GIA, TONG_TIEN)
VALUES
('HDCT001', 1, 1, 1, 2, 400000, 800000),
('HDCT002', 2, 2, 2, 1, 300000, 300000);

-- Thêm dữ liệu vào bảng DOI_TRA
INSERT INTO DOI_TRA (ID_KHACH_HANG, LY_DO_DOI, NGAY_DOI_TRA, TRANG_THAI, MO_MA, ID_HOA_DON_CHI_TIET)
VALUES
(1,N'Sai kích thước', GETDATE(), 1, N'Mô tả lỗi', 1),
(2, N'Lỗi sản phẩm', GETDATE(), 1, N'Mô tả lỗi', 2);

-- Thêm dữ liệu vào bảng SAN_PHAM_LOI
INSERT INTO SAN_PHAM_LOI (TEN_SAN_PHAM_LOI, MO_MA, ID_HOA_DON_CHI_TIET, SO_LUONG)
VALUES
(N'Áo thun nam lỗi', N'Lỗi may', 1, 2),
(N'Áo sơ mi nữ lỗi', N'Lỗi chất liệu', 2, 1);

-- Thêm dữ liệu vào bảng VOUCHER
INSERT INTO VOUCHER (MA_KHUYEN_MAI, MO_MA, TEN_KHUYEN_MAI, NGAY_KET_THUC, MUC_GIAM, TRANG_THAI, DIEU_KIEN_KHUYEN_MAI, MA_AP_DUNG, Loai, So_Luong)
VALUES
('VC001', N'Voucher giảm giá 10%', N'Giảm giá 10%', GETDATE() + 30, '10%', 1, N'Đơn hàng trên 500k', 'AP001', 1, '100'),
('VC002', N'Voucher giảm giá 20%', N'Giảm giá 20%', GETDATE() + 60, '20%', 1, N'Đơn hàng trên 1 triệu', 'AP002', 1, '50');

-- Thêm dữ liệu vào bảng HOA_DON_VOUCHER
INSERT INTO HOA_DON_VOUCHER (ID_VOUCHER, ID_HOA_DON_CHI_TIET, SO_TIEN_CON_LAI)
VALUES
(1, 1, 720000),
(2, 2, 240000);



SELECT * FROM SAN_PHAM_CHI_TIET
 select * from THUONG_HIEU   
  ALTER TABLE nhan_vien
DROP COLUMN chuc_vu
  ALTER TABLE nhan_vien
add chuc_vu bit
ALTER TABLE nhan_vien
ALTER COLUMN NGAY_TAO date
ALTER TABLE nhan_vien
ALTER COLUMN Ngay_sua date

