create
database Ban_Ao_DB
go
use Ban_Ao_DB

go

IF OBJECT_ID('THUONG_HIEU') IS NOT NULL
DROP TABLE THUONG_HIEU
CREATE TABLE THUONG_HIEU
(
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    TEN_THUONG_HIEU NVARCHAR(225) NOT NULL,
    NGAY_TAO        DATETIME DEFAULT GETDATE(),
    NGAY_SUA        DATETIME
) GO
IF OBJECT_ID('CHAT_LIEU') IS NOT NULL
DROP TABLE CHAT_LIEU
CREATE TABLE CHAT_LIEU
(
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    MA_CHAT_LIEU  VARCHAR(12),
    TEN_CHAT_LIEU NVARCHAR(225),
    TRANG_THAI    BIT,
    NGAY_TAO      DATETIME DEFAULT GETDATE(),
    NGAY_SUA      DATETIME
) GO
IF OBJECT_ID('DANH_MUC') IS NOT NULL
DROP TABLE DANH_MUC
CREATE TABLE DANH_MUC
(
    ID           INT IDENTITY(1,1) PRIMARY KEY,
    TEN_DANH_MUC NVARCHAR(225) NOT NULL,
    TRANG_THAI   BIT,
    NGAY_TAO     DATETIME DEFAULT GETDATE(),
    NGAY_SUA     DATETIME
) GO
IF OBJECT_ID('NHA_SAN_XUAT') IS NOT NULL
DROP TABLE NHA_SAN_XUAT
CREATE TABLE NHA_SAN_XUAT
(
    ID               INT IDENTITY(1,1) PRIMARY KEY,
    MA_NHA_SAN_XUAT  VARCHAR(12),
    TEN_NHA_SAN_XUAT NVARCHAR(225),
    TRANG_THAI       BIT,
    NGAY_TAO         DATETIME DEFAULT GETDATE(),
    NGAY_SUA         DATETIME
) GO
IF OBJECT_ID('CO_AO') IS NOT NULL
DROP TABLE CO_AO
CREATE TABLE CO_AO
(
    ID         INT IDENTITY(1,1) PRIMARY KEY,
    TEN_CO_AO  NVARCHAR(225),
    TRANG_THAI BIT,
    NGAY_TAO   DATETIME DEFAULT GETDATE(),
    NGAY_SUA   DATETIME
) GO
IF OBJECT_ID('SAN_PHAM') IS NOT NULL
DROP TABLE SAN_PHAM
CREATE TABLE SAN_PHAM
(
    ID                INT IDENTITY(1,1) PRIMARY KEY,
    MA_SAN_PHAM       VARCHAR(12),
    TEN_SAN_PHAM      NVARCHAR(255),
    ANH_SAN_PHAM      NVARCHAR(255),
    NGAY_TAO          DATETIME DEFAULT GETDATE(),
    NGAY_SUA          DATETIME,
    ID_DANH_MUC       INT,
    ID_NHA_SAN_XUAT   INT,
    SO_LUONG_SAN_PHAM INT,
    ID_THUONG_HIEU    INT,
    ID_CO_AO          INT,
    CONSTRAINT FK_SAN_PHAM_DANH_MUC FOREIGN KEY (ID_DANH_MUC) REFERENCES DANH_MUC (ID),
    CONSTRAINT FK_SAN_PHAM_NHA_SAN_XUA FOREIGN KEY (ID_NHA_SAN_XUAT) REFERENCES NHA_SAN_XUAT (ID),
    CONSTRAINT FK_SAN_PHAM_THUONG_HIEU FOREIGN KEY (ID_THUONG_HIEU) REFERENCES THUONG_HIEU (ID),
    CONSTRAINT FK_SAN_PHAM_CO_AO FOREIGN KEY (ID_CO_AO) REFERENCES CO_AO (ID),
) GO
IF OBJECT_ID('KICH_THUOC') IS NOT NULL
DROP TABLE KICH_THUOC
CREATE TABLE KICH_THUOC
(
    ID             INT IDENTITY(1,1) PRIMARY KEY,
    MA_KICH_THUOC  VARCHAR(10),
    TEN_KICH_THUOC NVARCHAR(225),
    TRANG_THAI     BIT,
    NGAY_TAO       DATETIME DEFAULT GETDATE(),
    NGAY_SUA       DATETIME
) GO
IF OBJECT_ID('MAU_SAC') IS NOT NULL
DROP TABLE MAU_SAC
CREATE TABLE MAU_SAC
(
    ID          INT IDENTITY(1,1) PRIMARY KEY,
    MA_MAU_SAC  VARCHAR(10),
    TEN_MAU_SAC NVARCHAR(225),
    TRANG_THAI  BIT,
    NGAY_TAO    DATETIME DEFAULT GETDATE(),
    NGAY_SUA    DATETIME,
) GO
IF OBJECT_ID('SAN_PHAM_CHI_TIET') IS NOT NULL
DROP TABLE SAN_PHAM_CHI_TIET
CREATE TABLE SAN_PHAM_CHI_TIET
(
    ID                         INT IDENTITY(1,1) PRIMARY KEY,
    ANH_SAN_PHAM_CHI_TIET      NVARCHAR(255),
    ID_SAN_PHAM                INT,
    ID_KICH_THUOC              INT,
    ID_MAU_SAC                 INT,
    ID_CHAT_LIEU               INT,
    SO_LUONG_SAN_PHAM_CHI_TIET INT,
    DON_GIA                    DECIMAL(10, 2),
    MO_TA                      NVARCHAR(255),
    NGAY_TAO                   DATETIME DEFAULT GETDATE(),
    NGAY_SUA                   DATETIME,
    TRANG_THAI                 BIT,
    CONSTRAINT FK_SAN_PHAM_CHI_TIET_CHAT_LIEU FOREIGN KEY (ID_CHAT_LIEU) REFERENCES CHAT_LIEU (ID),
    CONSTRAINT FK_SAN_PHAM_CHI_TIET_SAN_PHAM FOREIGN KEY (ID_SAN_PHAM) REFERENCES SAN_PHAM (ID),
    CONSTRAINT FK_SAN_PHAM_CHI_TIET_KICH_THUOC FOREIGN KEY (ID_KICH_THUOC) REFERENCES KICH_THUOC (ID),
    CONSTRAINT FK_SAN_PHAM_CHI_TIET_MAU_SAC FOREIGN KEY (ID_MAU_SAC) REFERENCES MAU_SAC (ID),
) GO

GO
IF OBJECT_ID('KHACH_HANG') IS NOT NULL
DROP TABLE KHACH_HANG
CREATE TABLE KHACH_HANG
(
    ID             INT IDENTITY(1,1) PRIMARY KEY,
    MA_KHACH_HANG  NVARCHAR(225),
    TEN_TAI_KHOAN  NVARCHAR(225),
    MAT_KHAU       VARCHAR(15),
    SO_DIEN_THOAI  VARCHAR(12),
    DIA_CHI        NVARCHAR(225),
    TEN_KHACH_HANG NVARCHAR(225),
    TRANG_THAI     BIT,
    NGAY_TAO       DATETIME DEFAULT GETDATE(),
    NGAY_SUA       DATETIME,
) GO
IF OBJECT_ID('GIO_HANG') IS NOT NULL
DROP TABLE GIO_HANG
CREATE TABLE GIO_HANG
(
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    ID_KHACH_HANG        INT,
    ID_SAN_PHAM_CHI_TIET INT,
    SO_LUONG             INT,
    TONG_TIEN            DECIMAL(10, 2),
    CONSTRAINT FK_GIO_HANG_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
    CONSTRAINT FK_GIO_HANG_SAN_PHAM_CHI_TIET FOREIGN KEY (ID_SAN_PHAM_CHI_TIET) REFERENCES SAN_PHAM_CHI_TIET (ID),
) GO
IF OBJECT_ID('NHAN_VIEN') IS NOT NULL
DROP TABLE NHAN_VIEN
CREATE TABLE NHAN_VIEN
(
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    TEN_NHAN_VIEN NVARCHAR(225),
    MA_NHAN_VIEN  VARCHAR(225),
    TEN_TAI_KHOAN VARCHAR(225),
    MAT_KHAU      VARCHAR(15),
    CHUC_VU       VARCHAR(255),
    TRANG_THAI    BIT,
    NGAY_TAO      DATETIME DEFAULT GETDATE(),
    NGAY_SUA      DATETIME,
) GO
IF OBJECT_ID('HOA_DON') IS NOT NULL
DROP TABLE HOA_DON
CREATE TABLE HOA_DON
(
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    ID_SAN_PHAM   INT,
    SO_LUONG      INT,
    DON_GIA       DECIMAL(10, 2),
    SO_DIEN_THOAI VARCHAR(12),
    ID_KHACH_HANG INT,
    TONG_TIEN     DECIMAL(10, 2),
    NGAY_MUA      DATETIME DEFAULT GETDATE(),
    TRANG_THAI    BIT,
    NGAY_TAO      DATETIME DEFAULT GETDATE(),
    NGAY_SUA      DATETIME,
    CONSTRAINT FK_HOA_DON_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
    CONSTRAINT FK_HOA_DON_SAN_PHAM FOREIGN KEY (ID_SAN_PHAM) REFERENCES SAN_PHAM (ID),
) GO
IF OBJECT_ID('THANH_TOAN') IS NOT NULL
DROP TABLE THANH_TOAN
CREATE TABLE THANH_TOAN
(
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    HINH_THUC_THANH_TOAN INT,
    ID_KHACH_HANG        INT,
    ID_HOA_DON           INT,
    CONSTRAINT FK_THANH_TOAN_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
    CONSTRAINT FK_THANH_TOAN_HOA_DON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON (ID),
) GO
IF OBJECT_ID('HOA_DON_CHI_TIET') IS NOT NULL
DROP TABLE HOA_DON_CHI_TIET
CREATE TABLE HOA_DON_CHI_TIET
(
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    ID_NHAN_VIEN         INT,
    ID_HOA_DON           INT,
    SO_LUONG             INT,
    DON_GIA              DECIMAL(10, 2),
    NGAY_TAO             DATETIME DEFAULT GETDATE(),
    NGAY_SUA             DATETIME,
    THANH_TIEN           DECIMAL(10, 2),
    HINH_THUC_THANH_TOAN NVARCHAR(255) ----- LƯU Ý-------
        CONSTRAINT FK_HOA_DON_CHI_TIET_NHAN_VIEN FOREIGN KEY (ID_NHAN_VIEN) REFERENCES NHAN_VIEN (ID),
    CONSTRAINT FK_HOA_DON_CHI_TIET_HOA_DON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON (ID),
) GO
IF OBJECT_ID('DOI_TRA') IS NOT NULL
DROP TABLE DOI_TRA
CREATE TABLE DOI_TRA
(
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    ID_KHACH_HANG        INT,
    LY_DO_DOI            NVARCHAR(255),
    NGAY_DOI_TRA         DATETIME,
    TRANG_THAI           BIT,
    MO_MA                NVARCHAR(255),
    ID_HOA_DON_CHI_TIET  INT,
    HINH_THUC_THANH_TOAN NVARCHAR(255) ----- LƯU Ý-------
        CONSTRAINT FK_DOI_TRA_KHACH_HANG FOREIGN KEY (ID_KHACH_HANG) REFERENCES KHACH_HANG (ID),
    CONSTRAINT FK_DOI_TRA_HOA_DON_CHI_TIET FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
) GO
IF OBJECT_ID('SAN_PHAM_LOI') IS NOT NULL
DROP TABLE SAN_PHAM_LOI
CREATE TABLE SAN_PHAM_LOI
(
    ID                  INT IDENTITY(1,1) PRIMARY KEY,
    TEN_SAN_PHAM_LOI    NVARCHAR(255),
    MO_MA               NVARCHAR(255),
    ID_HOA_DON_CHI_TIET INT,
    SO_LUONG            INT,
    CONSTRAINT FK_SAN_PHAM_LOI_HOA_DON_CHI_TIET FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
) GO
IF OBJECT_ID('VOUCHER') IS NOT NULL
DROP TABLE VOUCHER
CREATE TABLE VOUCHER
(
    ID                   INT IDENTITY(1,1) PRIMARY KEY,
    MA_KHUYEN_MAI        NVARCHAR(255),
    MO_MA                NVARCHAR(255),
    TEN_KHUYEN_MAI       NVARCHAR(255),
    NGAY_BAT_DAU         DATETIME DEFAULT GETDATE(),
    NGAY_KET_THUC        DATETIME,
    MUC_GIAM             VARCHAR(100),
    TRANG_THAI           BIT,
    DIEU_KIEN_KHUYEN_MAI NVARCHAR(255),
) GO
IF OBJECT_ID('HOA_DON_VOUCHER') IS NOT NULL
DROP TABLE HOA_DON_VOUCHER
CREATE TABLE HOA_DON_VOUCHER
(
    ID                  INT IDENTITY(1,1) PRIMARY KEY,
    ID_VOUCHER          INT,
    ID_HOA_DON_CHI_TIET INT,
    SO_TIEN_CON_LAI     DECIMAL(10, 2),
    CONSTRAINT FK_HOA_DON_VOUCHER_VOUCHER FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER (ID),
    CONSTRAINT FK_HOA_DON_VOUCHER_HOA_DON_CHI_TIEN FOREIGN KEY (ID_HOA_DON_CHI_TIET) REFERENCES HOA_DON_CHI_TIET (ID),
)
